// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#pragma once

#include "input/input_enums.hpp"
namespace sunkell {

	enum class button {
		unknown,

		// Keyboard buttons
		q,
		w,
		e,
		r,
		t,
		y,
		u,
		i,
		o,
		p,
		a,
		s,
		d,
		f,
		g,
		h,
		j,
		k,
		l,
		z,
		x,
		c,
		v,
		b,
		n,
		m,
		backtick,
		one,
		two,
		three,
		four,
		five,
		six,
		seven,
		eight,
		nine,
		zero,
		hyphen,
		equals,
		backspace,
		tab,
		caps_lock,
		left_shift,
		left_control,
		left_super,
		left_alt,
		space,
		right_alt,
		function,
		menu,
		right_super,
		right_control,
		right_shift,
		enter,
		backslash,
		left_brace,
		right_brace,
		semicolon,
		apostrophe,
		comma,
		period,
		slash,
		insert,
		home,
		page_up,
		del,
		end,
		page_down,
		escape,
		f1,
		f2,
		f3,
		f4,
		f5,
		f6,
		f7,
		f8,
		f9,
		f10,
		f11,
		f12,
		print_screen,
		scroll_lock,
		pause,
		num_lock,
		numpad_divide,
		numpad_multiply,
		numpad_minus,
		numpad_plus,
		numpad_enter,
		numpad_decimal,
		numpad_zero,
		numpad_one,
		numpad_two,
		numpad_three,
		numpad_four,
		numpad_five,
		numpad_six,
		numpad_seven,
		numpad_eight,
		numpad_nine,
		arrow_up,
		arrow_down,
		arrow_left,
		arrow_right,

		// Mouse buttons
		mouse_left,
		mouse_right,
		mouse_middle,
		mouse_x1,
		mouse_x2,

		// Controller buttons
		// TODO: Handle continuous axes
		controller_a,
		controller_b,
		controller_x,
		controller_y,
		controller_back,
		controller_guide,
		controller_start,
		controller_left_thumbstick,
		controller_right_thumbstick,
		controller_left_shoulder,
		controller_right_shoulder,
		controller_left_trigger,
		controller_right_trigger,
		controller_dpad_up,
		controller_dpad_down,
		controller_dpad_left,
		controller_dpad_right,
		controller_left_thumbstick_up,
		controller_left_thumbstick_down,
		controller_left_thumbstick_right,
		controller_left_thumbstick_left,
		controller_right_thumbstick_up,
		controller_right_thumbstick_down,
		controller_right_thumbstick_right,
		controller_right_thumbstick_left,
	};

	enum class button_state { down, up, unknown };

} // namespace sunkell
